### ISSUE TITLE
$ENV{GW_DEPS_ROOT} is undefined in samples\compiler\cmake\windows\CMakeLists.txt

### ISSUE THREAD

**Issue by jonathan-h-w** [ZP-Z/NvClothVS2022#1]
The environment variable isn't defined for some reason, causing its subsequent commands to fail. I fixed it by setting it at the beginning of the CMakeList:
`set(ENV{GW_DEPS_ROOT} ${NVCLOTH_ROOT_DIR}/../)`

Would be nice if there is an if statement to assert that the env var is defined

**Comment by ZP-Z** [comment]
Did the error occur while running './NvCloth/samples/CmakeGenerateProjects.bat'? 
Can you upload the error details, thanks

**Comment by ZP-Z** [comment]
Visual Studio call Cmake in the beginning,

**Comment by ZP-Z** [comment]
environment variable problem, already fixed. thanks for your suggestion!
